binop_separator = "Front"
condense_wildcard_suffixes = false
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
format_macro_matchers = false
format_strings = false
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "Mixed"
match_arm_blocks = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 100
reorder_impl_items = false
type_punctuation_density = "Wide"
use_field_init_shorthand = false
use_small_heuristics = "Max"
use_try_shorthand = false
