[package]
name = "bhwi-e2e-jade"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bitcoin.workspace = true
base64ct = { workspace = true, features = ["alloc"] }
bhwi-async.workspace = true
futures.workspace = true
hex.workspace = true
rand_core.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true

serde_cbor = "0.11.2"
