[package]
name = "bhwi-wasm"
version = "0.0.1"
edition = "2021"
authors = ["Edouard Paris <m@edouard.paris>"]
repository = "https://github.com/wizardsardine/bhwi"
license-file = "../LICENSE"
keywords = ["bitcoin",  "miniscript"]
description = "development kit"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait.workspace = true
bitcoin.workspace = true
bhwi.workspace = true
bhwi-async.workspace = true
console_log.workspace = true
console_error_panic_hook.workspace = true
futures.workspace = true
js-sys.workspace = true
log.workspace = true
getrandom.workspace = true
rand_core.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys.workspace = true
